Test OSX python3.8

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -58,20 +58,20 @@ matrix:
           packages:
             - libomp
           update: true
-      before_install: |
-        if [ -n "$IS_OSX" ]; then
-            TAPS="$(brew --repository)/Library/Taps"
-            if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
-                rm -rf "$TAPS/caskroom/homebrew-cask"
-            fi
-            find "$TAPS" -type d -name .git -exec \
-                    bash -xec '
-                        cd $(dirname '\''{}'\'') || echo "status: $?"
-                        git clean -fxd || echo "status: $?"
-                        sleep 1 || echo "status: $?"
-                        git status || echo "status: $?"' \; || echo "status: $?"
-            brew_cache_cleanup
-        fi
+#      before_install: |
+#        if [ -n "$IS_OSX" ]; then
+#            TAPS="$(brew --repository)/Library/Taps"
+#            if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
+#                rm -rf "$TAPS/caskroom/homebrew-cask"
+#            fi
+#            find "$TAPS" -type d -name .git -exec \
+#                    bash -xec '
+#                        cd $(dirname '\''{}'\'') || echo "status: $?"
+#                        git clean -fxd || echo "status: $?"
+#                        sleep 1 || echo "status: $?"
+#                        git status || echo "status: $?"' \; || echo "status: $?"
+#            brew_cache_cleanup
+#        fi
       before_cache: |
         # Cleanup dirs to be cached
         set -e; set -x
